### ISSUE TITLE
Action in test and train

### ISSUE THREAD

**Issue by onlytailei** [andrewliao11/pytorch-a3c-mujoco#1]
In both of the test and train procedure, the actions are all sampled from the Gaussian distribution.
Should the test thread just take the **_mu_** directly?

**Comment by onlytailei** [comment]
Another question, why not put the softplus for sigma in the model?

**Comment by andrewliao11** [comment]
if you prefer the stochastic policy, directly use gaussian distribution in testing. 
while many ppl tend to avoid stochastic policy when benchmarking. So depends on you 👍

**Comment by andrewliao11** [comment]
you mean why I use [this line](https://github.com/andrewliao11/pytorch-a3c-mujoco/blob/master/train.py#L66)

**Comment by onlytailei** [comment]
Yes, why not put this line in the model class and output the sigma_sq after softplus directly?

**Comment by andrewliao11** [comment]
both inside/outside the model is fine, in my opinion.
the main reason of putting it outside is that it reminds me that all ```sigma_sq``` is a positive number
